# Generated by Django 5.2.12 on 2026-04-02 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20260331_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='required_skills',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='必需技能(逗号分隔)'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='avatar',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='头像路径'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 2, 5, 47, 53, 870935, tzinfo=datetime.timezone.utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlist',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='重置Token'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='重置Token过期时间'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
