# Generated by Django 5.2.12 on 2026-04-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobdata_required_skills_userlist_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderinfo',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后爬取时间'),
        ),
        migrations.AddField(
            model_name='spiderinfo',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='idle', max_length=16, verbose_name='爬取状态'),
        ),
        migrations.AddField(
            model_name='userexpect',
            name='desired_education',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='期望学历'),
        ),
        migrations.AddField(
            model_name='userexpect',
            name='desired_experience',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='期望经验'),
        ),
        migrations.AddField(
            model_name='userexpect',
            name='desired_salary',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='期望薪资'),
        ),
    ]
