# Generated by Django 5.2.12 on 2026-04-02 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_spiderinfo_last_run_spiderinfo_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendlist',
            options={'managed': True, 'verbose_name': '投递记录', 'verbose_name_plural': '投递记录'},
        ),
        migrations.AlterModelOptions(
            name='spiderinfo',
            options={'managed': True, 'verbose_name': '爬虫信息', 'verbose_name_plural': '爬虫信息'},
        ),
        migrations.AlterModelOptions(
            name='userexpect',
            options={'managed': True, 'verbose_name': '求职期望', 'verbose_name_plural': '求职期望'},
        ),
        migrations.AlterField(
            model_name='sendlist',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job.jobdata', verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='sendlist',
            name='send_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='投递ID'),
        ),
        migrations.AlterField(
            model_name='sendlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job.userlist', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='spiderinfo',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='抓取数量'),
        ),
        migrations.AlterField(
            model_name='spiderinfo',
            name='page',
            field=models.IntegerField(blank=True, null=True, verbose_name='爬取页数'),
        ),
        migrations.AlterField(
            model_name='spiderinfo',
            name='spider_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='爬虫ID'),
        ),
        migrations.AlterField(
            model_name='spiderinfo',
            name='spider_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='爬虫名称'),
        ),
        migrations.AlterField(
            model_name='userexpect',
            name='expect_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='期望ID'),
        ),
    ]
