# Generated by Django 3.2.8 on 2026-04-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_sendlist_options_alter_spiderinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False, verbose_name='模型ID')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='模型名称')),
                ('endpoint_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='接入点ID')),
                ('model_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='模型类型')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='模型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模型配置',
                'verbose_name_plural': '模型配置',
                'db_table': 'model_config',
                'managed': True,
            },
        ),
    ]
