# Generated by Django 5.2.13 on 2026-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_modelconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpiderInfo',
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='api_url',
            field=models.CharField(blank=True, default='https://ark-cn-beijing.bytedance.net/api/v3/chat/completions', max_length=512, null=True, verbose_name='API地址'),
        ),
    ]
